In [8]:
import pandas as pd 

data = pd.read_csv("../datasets/Mental-Health-Twitter.csv", index_col=0)
data

post_id                    post_created  \
0      637894677824413696  Sun Aug 30 07:48:37 +0000 2015   
1      637890384576778240  Sun Aug 30 07:31:33 +0000 2015   
2      637749345908051968  Sat Aug 29 22:11:07 +0000 2015   
3      637696421077123073  Sat Aug 29 18:40:49 +0000 2015   
4      637696327485366272  Sat Aug 29 18:40:26 +0000 2015   
...                   ...                             ...   
19995  819336825231773698  Thu Jan 12 00:14:56 +0000 2017   
19996  819334654260080640  Thu Jan 12 00:06:18 +0000 2017   
19997  819334503042871297  Thu Jan 12 00:05:42 +0000 2017   
19998  819334419374899200  Thu Jan 12 00:05:22 +0000 2017   
19999  819334270825197568  Thu Jan 12 00:04:47 +0000 2017   

                                               post_text     user_id  \
0      It's just over 2 years since I was diagnosed w...  1013187241   
1      It's Sunday, I need a break, so I'm planning t...  1013187241   
2      Awake but tired. I need to sleep but my brain ...  1013187241   
3      RT @SewHQ: #Retro bears make perfect gifts and...  1013187241   
4      It’s hard to say whether packing lists are mak...  1013187241   
...                                                  ...         ...   
19995              A day without sunshine is like night.  1169875706   
19996  Boren's Laws: (1) When in charge, ponder. (2) ...  1169875706   
19997  The flow chart is a most thoroughly oversold p...  1169875706   
19998  Ships are safe in harbor, but they were never ...  1169875706   
19999     Black holes are where God is dividing by zero.  1169875706   

       followers  friends  favourites  statuses  retweets  label  
0             84      211         251       837         0      1  
1             84      211         251       837         1      1  
2             84      211         251       837         0      1  
3             84      211         251       837         2      1  
4             84      211         251       837         1      1  
...          ...      ...         ...       ...       ...    ...  
19995        442      230           7   1063601         0      0  
19996        442      230           7   1063601         0      0  
19997        442      230           7   1063601         0      0  
19998        442      230           7   1063601         0      0  
19999        442      230           7   1063601         0      0  

[20000 rows x 10 columns]

In [17]:
data2 = pd.read_csv("../datasets/Student Mental health.csv", index_col=0)
data2

Choose your gender   Age What is your course?  \
Timestamp                                                           
8/7/2020 12:02                  Female  18.0          Engineering   
8/7/2020 12:04                    Male  21.0    Islamic education   
8/7/2020 12:05                    Male  19.0                  BIT   
8/7/2020 12:06                  Female  22.0                 Laws   
8/7/2020 12:13                    Male  23.0         Mathemathics   
...                                ...   ...                  ...   
13/07/2020 19:56:49             Female  21.0                  BCS   
13/07/2020 21:21:42               Male  18.0          Engineering   
13/07/2020 21:22:56             Female  19.0             Nursing    
13/07/2020 21:23:57             Female  23.0     Pendidikan Islam   
18/07/2020 20:16:21               Male  20.0   Biomedical science   

                    Your current year of Study What is your CGPA?  \
Timestamp                                                           
8/7/2020 12:02                          year 1        3.00 - 3.49   
8/7/2020 12:04                          year 2        3.00 - 3.49   
8/7/2020 12:05                          Year 1        3.00 - 3.49   
8/7/2020 12:06                          year 3        3.00 - 3.49   
8/7/2020 12:13                          year 4        3.00 - 3.49   
...                                        ...                ...   
13/07/2020 19:56:49                     year 1        3.50 - 4.00   
13/07/2020 21:21:42                     Year 2        3.00 - 3.49   
13/07/2020 21:22:56                     Year 3        3.50 - 4.00   
13/07/2020 21:23:57                     year 4        3.50 - 4.00   
18/07/2020 20:16:21                     Year 2        3.00 - 3.49   

                    Marital status Do you have Depression?  \
Timestamp                                                    
8/7/2020 12:02                  No                     Yes   
8/7/2020 12:04                  No                      No   
8/7/2020 12:05                  No                     Yes   
8/7/2020 12:06                 Yes                     Yes   
8/7/2020 12:13                  No                      No   
...                            ...                     ...   
13/07/2020 19:56:49             No                      No   
13/07/2020 21:21:42             No                     Yes   
13/07/2020 21:22:56            Yes                     Yes   
13/07/2020 21:23:57             No                      No   
18/07/2020 20:16:21             No                      No   

                    Do you have Anxiety? Do you have Panic attack?  \
Timestamp                                                            
8/7/2020 12:02                        No                       Yes   
8/7/2020 12:04                       Yes                        No   
8/7/2020 12:05                       Yes                       Yes   
8/7/2020 12:06                        No                        No   
8/7/2020 12:13                        No                        No   
...                                  ...                       ...   
13/07/2020 19:56:49                  Yes                        No   
13/07/2020 21:21:42                  Yes                        No   
13/07/2020 21:22:56                   No                       Yes   
13/07/2020 21:23:57                   No                        No   
18/07/2020 20:16:21                   No                        No   

                    Did you seek any specialist for a treatment?  
Timestamp                                                         
8/7/2020 12:02                                                No  
8/7/2020 12:04                                                No  
8/7/2020 12:05                                                No  
8/7/2020 12:06                                                No  
8/7/2020 12:13                                                No  
...                                  

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   post_id       20000 non-null  int64 
 1   post_created  20000 non-null  object
 2   post_text     20000 non-null  object
 3   user_id       20000 non-null  int64 
 4   followers     20000 non-null  int64 
 5   friends       20000 non-null  int64 
 6   favourites    20000 non-null  int64 
 7   statuses      20000 non-null  int64 
 8   retweets      20000 non-null  int64 
 9   label         20000 non-null  int64 
dtypes: int64(8), object(2)
memory usage: 1.7+ MB


In [10]:
# import nltk
# from nltk import stopwords

from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
x = vec.fit_transform(data['post_text'])

#print(vec.vocabulary_)
print(x.toarray())
print()
print(x.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

(20000, 32428)


In [15]:
data['post_text']

0        It's just over 2 years since I was diagnosed w...
1        It's Sunday, I need a break, so I'm planning t...
2        Awake but tired. I need to sleep but my brain ...
3        RT @SewHQ: #Retro bears make perfect gifts and...
4        It’s hard to say whether packing lists are mak...
                               ...                        
19995                A day without sunshine is like night.
19996    Boren's Laws: (1) When in charge, ponder. (2) ...
19997    The flow chart is a most thoroughly oversold p...
19998    Ships are safe in harbor, but they were never ...
19999       Black holes are where God is dividing by zero.
Name: post_text, Length: 20000, dtype: object

In [12]:
y = data["label"]
y

0        1
1        1
2        1
3        1
4        1
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: label, Length: 20000, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y)
[i.shape for i in [x_train, x_test, y_train, y_test]]

[(15000, 32428), (5000, 32428), (15000,), (5000,)]

In [14]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.8444

In [16]:
new_reviews = ["Suffering so bad...I wanna kill myself", "My emotions are more stable now thanks to some gaming...finally", "I wanna drink more coke...the carbonation hits my brain really well", "meh"]
review_vector = vec.transform(new_reviews)

display(review_vector)

model.predict(review_vector)


<4x32428 sparse matrix of type '<class 'numpy.int64'>'
	with 28 stored elements in Compressed Sparse Row format>

array([1, 1, 1, 1], dtype=int64)